default: &default
adapter: postgresql
encoding: unicode
pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
# host: <%= ENV.fetch('DB_HOST', 'localhost') %>
# username: <%= ENV.fetch('DB_USERNAME', 'postgress') %>
# password: <%= ENV.fetch('DB_PASSWORD', 'postgress') %>

development:
<<: *default
database: ireporter_development

test:
<<: *default
database: ireporter_test

production:
<<: *default
database: ireporter_production
url: <%= ENV['DATABASE_URL'] %>